kind: pipeline
type: docker
name: test_semantic-release

clone:
  depth: 50

steps:
  # - name: install
  #   image: node:14.18.0-buster
  #   commands:
  #     - npm install --silent
  #   when:
  #     branch:
  #       - master
  #       - develop
  # - name: unit-test
  #   image: node:14.18.0-buster
  #   commands:
  #     - npm test
  #   when:
  #     branch:
  #       - master
  #       - develop
  - name: release
    image: node:14.18.0-buster
    environment:
      GIT_AUTHOR_NAME: renhz
      GIT_AUTHOR_EMAIL: ren.zheng@maxwin.com.tw
      GIT_COMMITTER_NAME: ${DRONE_COMMIT_AUTHOR_NAME}
      GIT_COMMITTER_EMAIL: ${DRONE_COMMIT_AUTHOR_EMAIL}
      GIT_CREDENTIALS:
        from_secret: bitbucket_username_password
    commands:
      - npx semantic-release
    when:
      branch:
        - master
        - release
      event:
        - push
  # - name: push
  #   image: plugins/docker
  #   settings:
  #     repo: cicd-so-happy.maxwin.com.tw:5000/test_semantic-release
  #     registry: cicd-so-happy.maxwin.com.tw:5000
  #     tags: ${DRONE_TAG}
  #     insecure: true
  #   when:
  #     event:
  #       - tag